all:
	gcc -g bss.c -o bss.exe
	gcc -g data.c -o data.exe
	gcc -g heap_error.c -o heap_error_test
	gcc -g toupper.c -o toupper_test
	gcc -g dlist.c dlist_toupper.c -o dlist_toupper_test
clean:
	rm -f *test *.exe
